### PR TITLE
Add Cron Runner graceful service exit

### PR DESCRIPTION
**Pull request by darthhexx**
* Move away from ranging over timer ticks to a `waitForEpoch` utility function, which allows us to keep an eye on signal handling.
* Add global variables to monitor service routines and worker running states for graceful exit.

### CODE REVIEW

**Comment by darthhexx** [comment]
Fixes #152

**Comment by darthhexx** [comment]
Okay. It will never exit unless it feels it is time to do so :) (bar SIGKILL of course)

I'll do some more testing, because TBH I just squeezed this development in between other things and I had a feeling this may be the case.

**Comment by darthhexx** [comment]
@ethitter this is fixed now, according to my testing without events anyway. Can you double check for me please?

**Comment by ethitter** [comment]
@darthhexx This is better, but I'm still able to get the thing stuck while shutting down. It looks like the site retrievers don't always die, and it gets stuck waiting for them to.

**Comment by darthhexx** [comment]
I have been unable to recreate the issue of site retrievers getting stuck after 36 attempts with different settings. Even with 50 of both worker types running and a get events interval of 2s they are all shutting down as expected.

Those results, together with the fact that the init script will `SIGKILL` the app after 60 seconds anyway, I am going to go ahead with this code in production.

If you have a particular set of settings and/or steps when you encounter the issue, please could you send them to me?

**Comment by darthhexx** [comment]
@mjangda this is already in production, so I'd appreciate a quick review so I can merge.

**Pull request merged**
