### PR TITLE
WIP: Switch locks to individual cache keys

### LINKED ISSUE #3: Lock: Add tests for `Lock` class

### PR DESCRIPTION
**Pull request by ethitter**
Fixes #3

### CODE REVIEW

**Comment by ethitter** [comment]
The multi-concurrency locks shouldn't be freed blindly as they are in 44c722f; it's a stepping stone.

**Comment by ethitter** [comment]
This was a silly approach. Instead of an array of locks, each numbered lock should be it's own cache. They expire on their own, and the class can handle some magic to make the many caches appear as a coherent lock. This has the added benefit of allowing for substitution of MySQL's `GET_LOCK()` or something Redis-backed, etc.

**Comment by WPprodigy** [comment]
> Instead of an array of locks, each numbered lock should be it's own cache.

Definitely agree. While the array is better than the current situation where it's not able to really purge out abandoned locks, having all locks share a cache key leads to pretty unfortunate race conditions.

Letting locks have their own, and using `wp_cache_add()` even for further race-condition prevention, this will be much more sustainable. A "real" `wp_cache_get_multiple()` will also help a lot so it can pull them all at once.

____

For future readers, this will help solve the problem where a job is killed off (OOMs) higher up in the stack and is never able to release its lock. Since jobs will keep running and refreshing the lock timestamp, the "slot" of this OOM'd job will be forever taken until finally all slots are deadlocked and it can recognize that and wipe the all cache key out.

**Comment by WPprodigy** [comment]
Closing this as it's a bit stale. Tracking in https://github.com/Automattic/Cron-Control/issues/233.

**Pull request closed without merging**
