### PR TITLE
Initial pass at enabling alternative storage for Event_Store using hooks

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Added a number of filters that allow for overriding `$wpdb` interaction with the Cron Control table. This would allow for many other stores to be utilized instead, using a few hooks.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
More work to be done since $wpdb is talking to the custom table outside of Event_Store (which the code really shouldn't be, should it?)

**Comment by ethitter** [comment]
Interesting! At first glance, I like this idea.

> which the code really shouldn't be, should it?

Heh, no, it should not. The custom table was added in version 2, so I'm not entirely surprised that there are table references outside of the `Events_Store` class, but still, that's not intentional.

**Comment by sc0ttkclark** [comment]
Thanks :)

Will see what I can do to adjust things everywhere else too.

**Comment by mjangda** [comment]
Out of curiosity, what alternate store would you want to use?

Also, might be cleaner just to override the `Events_Store` completely and allow swapping in an alternate class (instead of a new filter for each data operation we need to do)?

**Comment by WPprodigy** [comment]
Think we can close this as it's a bit stale now, but I do agree that ideally `Events_Store` itself would be the overridable piece (or perhaps a subset of it that implements the basic CRUD operations).

**Pull request closed without merging**
