### PR TITLE
Support WP 5.1's new cron hooks

### LINKED ISSUE #173: Events: Use preflight filters added in WP 5.1
**Task**
When setting and getting Cron jobs, make use of the new WP filters: `pre_schedule_event`, `pre_reschedule_event`, `pre_unschedule_event`, `pre_clear_scheduled_hook`, `pre_unschedule_hook`, `pre_get_scheduled_event`, `pre_next_scheduled` and `pre_get_ready_cron_jobs`.

**Background**
In WordPress 5.1, new filters will be added to preflight event scheduling to allow for custom Cron storage systems.

The filters were added in [WordPress#32656](https://core.trac.wordpress.org/ticket/32656) (see WordPress/wordpress-develop@a32ea2d35d2fcf7bccf54ff7abfad9a2b49ee360) and [WordPress#45797](https://core.trac.wordpress.org/ticket/45797) (see WordPress/wordpress-develop@0bc20594c78369a6778635cd58f2b90c57428d6d).

### PR DESCRIPTION
**Pull request by ethitter**
5.1 will introduce a new set of filters that we can use to intercept all cron-scheduling operations. 

Outstanding items:
- [ ] Introduce helper to replace `get_option( 'cron' )` calls with `Events_Store` methods.
- [x] Tests

Fixes #173 
Ports #174 from `ethitter/Cron-Control`

### CODE REVIEW

**Comment by ethitter** [comment]
Continuing from #174 now that the branch is in the main repo.

**Comment by nickdaugherty** [comment]
@ethitter I've made some tweaks (everything but the `get_option( 'cron' )` helper) - can you let me know if you think the tests I added are sufficient?

**Comment by nickdaugherty** [comment]
To keep the scope tighter, I say we punt the `get_option( 'cron' )` stuff to a future PR.

**Comment by nickdaugherty** [comment]
This has been running on a handful of VIP Go sites, mostly trouble-free, but one site ended up creating some duplicate record errors:

```
[05-May-2019 11:53:22 UTC] WordPress database error Duplicate entry '1557043200-refer<redacted-action-name>-40cd750bba9870f18aada2478b24840a-' for key 'ts_action_instance_status' for query INSERT INTO `wp_a8c_cron_control_jobs` (`timestamp`, `action`, `action_hashed`, `instance`, `args`, `last_modified`, `created`) VALUES ('1557043200', '<redacted-action-name>', '062931c1cec30d83bd65834edb8ab360', '40cd750bba9870f18aada2478b24840a', 'a:0:{}', '2019-05-05 11:53:22', '2019-05-05 11:53:22') made by Automattic\WP\Cron_Control\Events_Store::create_or_update_job
```

I found a logic bug in the theme that caused the same event to get rescheduled in the past as soon as it started running, but I'm not sure why that situation now causes duplicate entry errors where before there were none. Perhaps something to do with checking the DB directly, rather than checking the value of the cron option (which could be out of date b/c cached in memcache and process memory), before rescheduling.

**Comment by ethitter** [comment]
That's been an intermittent, but persistent, issue from early on; it was partly why we moved from a post type to the custom table, because it allowed the unique constraint to be added. I've seen this on small and large sites alike, on VIP Go and elsewhere. Anecdotally, I've experienced it less while running this branch, but my insight is limited. Parsing changes to the cron option, and reconstructing it when the queue is large, doesn't scale very well, so I'm not entirely surprised. 😆

**Comment by nickdaugherty** [comment]
I think we'll need to add caching as I'm seeing a sharp uptick in SELECT queries per second on this branch, as we're no longer checking the cached option and instead hitting the DB directly via the filters.

Screen Shot 2019-05-09 at 3 53 03 PM

**Comment by ethitter** [comment]
Heh, yeah, not including caching was a big error on my part. The `Events_Store` clearly needs some love.

**Comment by ethitter** [comment]
Something to be aware of if this is revisited: https://github.com/Automattic/Cron-Control/issues/199

**Comment by WPprodigy** [comment]
Closing in favor of https://github.com/Automattic/Cron-Control/pull/219

**Pull request closed without merging**
